version: "3.8"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_SERVICES=s3,sqs # Chỉ bật các dịch vụ S3 và SQS
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    volumes:
      - "./data/localstack:/var/lib/localstack" # Lưu dữ liệu LocalStack ra ngoài container
  mysql:
    container_name: file_process_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=accounting_system
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - "./data/mysql:/var/lib/mysql"

  redis:
    image: redis:6.2-alpine
    container_name: file_process_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
