// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/aws/aws-sdk-go-v2/aws"
	"gofile/internal/controller"
	"gofile/internal/repository"
	"gofile/internal/service"
	"gofile/internal/worker"
	"gofile/pkg/aws"
)

// Injectors from export_csv_wire.go:

func InitExportCsvRouterHandler() (*ExportHandlers, error) {
	config := provideAWSConfig()
	sqsService := paws.NewSQSService(config)
	s3Service := paws.NewS3Service(config)
	accountRepository := repository.NewAccountRepository()
	exportCsvService := service.NewExportCsvService(sqsService, s3Service, accountRepository)
	exportCsvController := controller.NewExportCsvController(exportCsvService)
	exportCsvWorker := worker.NewExportCsvWorker(exportCsvService)
	exportHandlers := &ExportHandlers{
		Controller: exportCsvController,
		Worker:     exportCsvWorker,
	}
	return exportHandlers, nil
}

// export_csv_wire.go:

// Provide AWS Config
func provideAWSConfig() aws.Config {
	return paws.LoadAWSConfig()
}

type ExportHandlers struct {
	Controller *controller.ExportCsvController
	Worker     *worker.ExportCsvWorker
}
